# Generated by Django 4.2.1 on 2023-08-27 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WebApi', '0002_products_likes_products_reviews_alter_likes_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='product',
            new_name='products',
        ),
        migrations.RemoveField(
            model_name='products',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='products',
            name='reviews',
        ),
        migrations.AlterField(
            model_name='likes',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApi.products'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApi.products'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
