# Generated by Django 4.2.1 on 2023-08-28 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebApi', '0006_remove_orderdetail_order_products_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eachorderproduct',
            old_name='order',
            new_name='orderid',
        ),
        migrations.RemoveField(
            model_name='eachorderproduct',
            name='productprice',
        ),
        migrations.AddField(
            model_name='eachorderproduct',
            name='price',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='product_price', to='WebApi.products'),
        ),
    ]
