# Generated by Django 4.2.1 on 2023-08-28 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WebApi', '0009_remove_eachorderproduct_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordertime', models.DateTimeField()),
                ('totalprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_doer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='ordertime',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='totalprice',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='user',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='WebApi.products'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='quantity',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.DeleteModel(
            name='EachOrderProduct',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='order',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='orderdetail', to='WebApi.order'),
        ),
    ]
