# Generated by Django 4.2.1 on 2023-08-28 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApi', '0010_order_remove_orderdetail_ordertime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderDetail',
        ),
    ]
