# Generated by Django 4.2.1 on 2023-09-03 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebApi', '0014_orderdetail_eachproductdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eachproductdetail',
            name='orderid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eachproductdetail', to='WebApi.orderdetail'),
        ),
    ]
