# Generated by Django 4.2.1 on 2023-09-04 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApi', '0015_alter_eachproductdetail_orderid'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='comments',
            field=models.CharField(default='Review Done', max_length=10000),
        ),
    ]
