# Generated by Django 4.2.1 on 2023-09-10 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApi', '0017_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='address',
            field=models.CharField(default='PINDI', max_length=999),
        ),
    ]
